<?php

namespace Walid\BlogBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\Tools\Pagination\Paginator;

/**
 * ArticleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ArticleRepository extends EntityRepository
{
  public function getArticles($page,$nbPerPage,$categoryId)
  {
    // Query the DB to get all articles.
    $queryBis = $this->createQueryBuilder('a')
    ->leftJoin('a.image', 'i')
    ->addSelect('i')
    ->leftJoin('a.categories', 'c')
    ->addSelect('c')
    ->orderBy('a.date', 'DESC')
    ;

    if ($categoryId != null)
      $queryBis->where('c.id = '.$categoryId);

    $query = $queryBis->getQuery();
    $query

    ->setFirstResult(($page-1) * $nbPerPage)
    ->setMaxResults($nbPerPage)
    ;

    // return the query paginate
    return new Paginator($query, true);
  }
}
