<?php

namespace Walid\BlogBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * CategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategoryRepository extends EntityRepository
{
    public function getCategories()
  {
    // Get all categories
    $query = $this->createQueryBuilder('a')
    ->orderBy('a.name', 'DESC')
    ->getQuery()
    ;

    return $query->getResult();
  }
}
